version: '3.7'
services:
  php:
    volumes:
      - .:/var/www/html/
    networks:
      - web-public
    ####################################
    # Local development config
    ####################################
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financial-freedom.rule=Host(`financial-freedom.dev.test`)"
      - "traefik.http.routers.financial-freedom.entrypoints=websecure"
      - "traefik.http.routers.financial-freedom.tls=true"
      - "traefik.http.services.financial-freedom.loadbalancer.server.port=443"
      - "traefik.http.services.financial-freedom.loadbalancer.server.scheme=https"

  node:
    image: node:lts
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks: 
      - web-public
  
  meilisearch:
    hostname: "financial-freedom_meilisearch"
    image: getmeili/meilisearch
    volumes: 
      - ./volumes/meilisearch/data.ms:/data.ms
    networks:
      - web-public

  redis:
    hostname: "financial-freedom_redis"
    image: redis:6
    command: "redis-server --appendonly yes --requirepass redispassword"
    volumes:
     - ./volumes/redis/data:/data
    networks:
     - web-public

networks:
  web-public:
    external: true